[[redirects]]
  from = "/scripts/*"
  to = "https://datan-owhdhhenduxdbidb.zh-tw.eu.org/scripts/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "https://gfork.zh-tw.eu.org/:splat"
  status = 307